### ISSUE TITLE
entrypoint.sh cannot be found

### ISSUE THREAD

**Issue by iftekharahmed0427** [PinkFloyd1213/RVC-All-In-One#2]
it's just as the title says, I have tried to run this in runpod, and it gives me an error saying [entrypoing.sh cannot be found]

**Comment by PinkFloyd1213** [comment]
I used it yesterday after the update with no issues on RunPod. To be sure, I just tried to recreate a pod just now and encountered no issues running it.

Did you use directly my template ? The link: https://runpod.io/console/deploy?template=ibol2g7pbw&ref=xvopf8xp

**Comment by iftekharahmed0427** [comment]
That's weird, yes I'm running it directly, do I need specific type of machine? Do you have discord?

**Comment by iftekharahmed0427** [comment]
This is what I am getting: https://prnt.sc/YZulSt5S_4D9
The pod: https://prnt.sc/DcXClbHiUAkP

**Comment by PinkFloyd1213** [comment]
Well I don't know why this is happening, but I've just tested it on the same machine as you, in secure cloud, and I'm having the same problem. On the other hand, if I use an A4500 in community cloud, everything works without a hitch... 

Maybe it's a problem with the secure server, even if it's very strange. 

You can look in the Dockerfile, the code to create the entrypoint is there...

![image](https://github.com/PinkFloyd1213/RVC-AIO/assets/31860086/5a6cab34-3923-4db1-a3a8-3f1b0d1e9f5c)
![image](https://github.com/PinkFloyd1213/RVC-AIO/assets/31860086/0f678484-9f10-4e60-b131-9658dc192aea)

**Comment by iftekharahmed0427** [comment]
whoa! it does work, thanks lol

guess secure cloud is too secure

**Comment by iftekharahmed0427** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'assets/rmvpe/rmvpe.pt'

Also can this be something I can fix?

**Comment by PinkFloyd1213** [comment]
It's a concern that's been with us for some time. I can try to fix it. I'll keep you posted.

**Comment by PinkFloyd1213** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'assets/rmvpe/rmvpe.pt'
> 
> Also can this be something I can fix?

It's fixed. Just pull the latest docker image.

**Comment by iftekharahmed0427** [comment]
> > FileNotFoundError: [Errno 2] No such file or directory: 'assets/rmvpe/rmvpe.pt'
> > Also can this be something I can fix?
> 
> It's fixed. Just pull the latest docker image.

Oh alright, just to let you know, the vocal/instrument removal also doesn't work

**Comment by PinkFloyd1213** [comment]
I have open an issue for that @nanashiz2 

https://github.com/PinkFloyd1213/RVC-AIO/issues/3#issue-2369326450
